### PR TITLE
Hey There

### PR DESCRIPTION
**Pull request by insomnyawolf**
I have been doing a bit of work over that. Here are my lastest changes! =)

### CODE REVIEW

**Comment by Kovaelin** [comment]
Thanks!

**Comment by insomnyawolf** [comment]
Im Still Struggling with visual stuff if you wanna help or talk about ideas tell me, it's always wellcome.

**Comment by Kovaelin** [comment]
I haven't started looking at it much yet. I'm just looking at a bunch of interesting resources before diving in. One thing I thought about right away though, was to see if it might be possible to use a single search box, with different buttons. Something like this: https://i.imgur.com/qprCHDQ.png

**Comment by insomnyawolf** [comment]
It is possible, if you want later today we can take a look at it ( also sorry for late answer)

**Pull request merged**
